
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ntsak
 */
public class AttendeeRegistration extends javax.swing.JFrame {

    /**
     * Creates new form AttendeeRegistration
     */
    public AttendeeRegistration() {
        initComponents();
    }
private void clearEventTable(){
      DefaultTableModel table = (DefaultTableModel)EventTable.getModel();
        table.setRowCount(0);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AttendeeTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        AttendeeName = new javax.swing.JTextField();
        AttendeeSurname = new javax.swing.JTextField();
        AttendeeContact = new javax.swing.JTextField();
        AttendeeEmail = new javax.swing.JTextField();
        AttendeeEventName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        EventTable = new javax.swing.JTable();
        EventList = new javax.swing.JButton();
        AttendeeCreatebtn = new javax.swing.JButton();
        AttendeeList = new javax.swing.JButton();
        AttendeeUpdate = new javax.swing.JButton();
        AttendeeDelete = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ATTENDEE REGISTRATION");

        jLabel2.setText("NAME");

        jLabel3.setText("SURNAME");

        jLabel4.setText("CONTACT");

        jLabel5.setText("EMAIL");

        AttendeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "SURNAME", "CONTACT", "EMAIL", "EVENT NAME"
            }
        ));
        AttendeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttendeeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AttendeeTable);

        jLabel6.setText("EVENT ATTENDING");

        EventTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Name", "Date"
            }
        ));
        jScrollPane2.setViewportView(EventTable);

        EventList.setText("Show Event ");
        EventList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventListActionPerformed(evt);
            }
        });

        AttendeeCreatebtn.setText("INSERT");
        AttendeeCreatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendeeCreatebtnActionPerformed(evt);
            }
        });

        AttendeeList.setText("VIEW ATTENDEE LIST");
        AttendeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendeeListActionPerformed(evt);
            }
        });

        AttendeeUpdate.setText("UPDATE");
        AttendeeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendeeUpdateActionPerformed(evt);
            }
        });

        AttendeeDelete.setText("DELETE");
        AttendeeDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendeeDeleteActionPerformed(evt);
            }
        });

        previous.setText("Previous Frame");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        jButton1.setText("Next Frame");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AttendeeName)
                            .addComponent(AttendeeSurname)
                            .addComponent(AttendeeContact)
                            .addComponent(AttendeeEmail)
                            .addComponent(AttendeeEventName, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(EventList)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AttendeeCreatebtn)
                        .addGap(18, 18, 18)
                        .addComponent(AttendeeList)
                        .addGap(18, 18, 18)
                        .addComponent(AttendeeUpdate)
                        .addGap(28, 28, 28)
                        .addComponent(AttendeeDelete)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previous)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AttendeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AttendeeSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AttendeeContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AttendeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(AttendeeEventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EventList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(133, 133, 133)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AttendeeCreatebtn)
                    .addComponent(AttendeeList)
                    .addComponent(AttendeeUpdate)
                    .addComponent(AttendeeDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previous)
                    .addComponent(jButton1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EventListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventListActionPerformed
      clearEventTable();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event_planner", "root", "Boitekong2003");
        
        Statement stm3 = con.createStatement();
        String  sql3 = "SELECT * FROM event_table";
        ResultSet result = stm3.executeQuery(sql3);
        
        while(result.next()){
            String EventName = result.getString("Event_Name");
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
  Date eventDate = result.getDate("Event_Date");
  String Date = dateFormat.format(eventDate);
                     
                     String tableData[] ={EventName,Date};
                     DefaultTableModel table = (DefaultTableModel)EventTable.getModel();
                     table.addRow(tableData);
                     
        }
        
        
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex); 
        }
    }//GEN-LAST:event_EventListActionPerformed

    private void AttendeeCreatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendeeCreatebtnActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event_planner", "root", "Boitekong2003");
            
            String SQL = "INSERT INTO attendee_information(Name,Last_Name, Contact_Details, Email,Event_Attending) VALUES(?, ?, ?, ?,?)";
            PreparedStatement STATE2= con.prepareCall(SQL);
            STATE2.setString(1, AttendeeName.getText());
            STATE2.setString(2, AttendeeSurname.getText());
            STATE2.setString(3, AttendeeContact.getText());
            STATE2.setString(4, AttendeeEmail.getText());
            STATE2.setString(5, AttendeeEventName.getText());
         
            STATE2.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully inserted the data to the database");
            clearFields();
        } catch (Exception ex) {
        if (((SQLException) ex).getErrorCode()==1062) {
JOptionPane.showMessageDialog(null,"Duplicate Entry");
}else {
      JOptionPane.showMessageDialog(null, "SQL Error "+ex.getMessage());      
        }
        }  
    }//GEN-LAST:event_AttendeeCreatebtnActionPerformed

    private void AttendeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendeeListActionPerformed
        clear();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
                 java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event_planner", "root", "Boitekong2003");
       
         Statement stm = con.createStatement();
        String  sql = "SELECT * FROM attendee_information;";
        ResultSet result = stm.executeQuery(sql);
        
        while(result.next()){
            String AttendeeName = result.getString("Name");
               String AttendeeSurname = result.getString("Last_Name");
                  String AttendeeContact = result.getString("Contact_Details");
                     String AttendeeEmail = result.getString("Email");
                     String AttendeeEventName = result.getString("Event_Attending");
                    
 
                     String tableData[] ={AttendeeName, AttendeeSurname,AttendeeContact,AttendeeEmail,AttendeeEventName};
                     DefaultTableModel table = (DefaultTableModel)AttendeeTable.getModel();
                     table.addRow(tableData);
                     
        }
           
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex); 
        }
        
    }//GEN-LAST:event_AttendeeListActionPerformed

    private void clear(){
      DefaultTableModel table = (DefaultTableModel)AttendeeTable.getModel();
        table.setRowCount(0);}

    private void clearFields(){
        AttendeeName.setText("");
          AttendeeSurname.setText("");
            AttendeeContact.setText("");
              AttendeeEmail.setText("");
                AttendeeEventName.setText("");
    }
    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
   
     EventPlanning frame1= new EventPlanning();
       frame1.setVisible(true);
       dispose();                 
    }//GEN-LAST:event_previousActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       VanueManagement frame3= new VanueManagement();
       frame3.setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AttendeeUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendeeUpdateActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event_planner", "root", "Boitekong2003");
        String SQL2 = "UPDATE attendee_information SET Name = ?, Last_Name = ?, Contact_Details= ?,Email = ?,Event_Attending=?";
            
        PreparedStatement STATE = con.prepareStatement(SQL2);
                STATE.setString(1, AttendeeName.getText());
            STATE.setString(2, AttendeeSurname.getText());
            STATE.setString(3, AttendeeContact.getText());
            STATE.setString(4, AttendeeEmail.getText());
            STATE.setString(5,AttendeeEventName.getText());
          
            
            int rowsUpdated = STATE.executeUpdate();
            if (rowsUpdated > 0) {
                
               JOptionPane.showMessageDialog(null,"Update successful");
            } else {
                
                JOptionPane.showMessageDialog(null,"Update failed");
            }
        } catch (SQLException ex) {
           
         JOptionPane.showMessageDialog(null,"Error updating data: " + ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EventPlanning.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_AttendeeUpdateActionPerformed

    private void AttendeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendeeTableMouseClicked
       DefaultTableModel model = (DefaultTableModel) AttendeeTable.getModel();
           int row = AttendeeTable.rowAtPoint(evt.getPoint());
       
        int rows = AttendeeTable.getSelectedRowCount();

        if (rows == 1) {
       
        
        AttendeeName.setText(model.getValueAt(row, 0).toString());
          AttendeeSurname.setText(model.getValueAt(row, 1).toString());
          AttendeeContact.setText(model.getValueAt(row, 2).toString());
          AttendeeEmail.setText(model.getValueAt(row, 3).toString());
          AttendeeEventName.setText(model.getValueAt(row,4).toString());
        }
    }//GEN-LAST:event_AttendeeTableMouseClicked

    private void AttendeeDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendeeDeleteActionPerformed
       try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             java.sql.Connection con3 = DriverManager.getConnection("jdbc:mysql://localhost:3306/event_planner", "root", "Boitekong2003");
            
       String SQL = "DELETE FROM attendee_information WHERE Name = ?";
PreparedStatement STATE3 = con3.prepareStatement(SQL);
            

            STATE3.setString(1, AttendeeName.getText());
            
            STATE3.executeUpdate();
         JOptionPane.showMessageDialog(null, "Successfully Deleted");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AttendeeRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AttendeeRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AttendeeDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendeeRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendeeRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendeeRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendeeRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendeeRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AttendeeContact;
    private javax.swing.JButton AttendeeCreatebtn;
    private javax.swing.JButton AttendeeDelete;
    private javax.swing.JTextField AttendeeEmail;
    private javax.swing.JTextField AttendeeEventName;
    private javax.swing.JButton AttendeeList;
    private javax.swing.JTextField AttendeeName;
    private javax.swing.JTextField AttendeeSurname;
    private javax.swing.JTable AttendeeTable;
    private javax.swing.JButton AttendeeUpdate;
    private javax.swing.JButton EventList;
    private javax.swing.JTable EventTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton previous;
    // End of variables declaration//GEN-END:variables
}
