
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ntsak
 */
public class VanueManagement extends javax.swing.JFrame {

    /**
     * Creates new form VanueManagement
     */
    public VanueManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        VenueAvailability = new javax.swing.JTextField();
        VenueName = new javax.swing.JTextField();
        VenueCapacity = new javax.swing.JTextField();
        VenueAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        VanueTable = new javax.swing.JTable();
        VanueCreatebtn = new javax.swing.JButton();
        VanueUpdatebtn = new javax.swing.JButton();
        VanueViewbtn = new javax.swing.JButton();
        VanueDeletebtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("VANUE MANAGEMENT");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Vanue Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Vanue Address");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Vanue Capacity");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Vanue Availability");

        VenueCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenueCapacityActionPerformed(evt);
            }
        });

        VanueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Venue Name", "Address", "Venue Capacity", "Venue Availability"
            }
        ));
        VanueTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VanueTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(VanueTable);

        VanueCreatebtn.setText("Create");
        VanueCreatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VanueCreatebtnActionPerformed(evt);
            }
        });

        VanueUpdatebtn.setText("Update");
        VanueUpdatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VanueUpdatebtnMouseClicked(evt);
            }
        });
        VanueUpdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VanueUpdatebtnActionPerformed(evt);
            }
        });

        VanueViewbtn.setText("View");
        VanueViewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VanueViewbtnActionPerformed(evt);
            }
        });

        VanueDeletebtn.setText("Delete");
        VanueDeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VanueDeletebtnActionPerformed(evt);
            }
        });

        jButton5.setText("Previous Frame");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VenueName)
                            .addComponent(VenueAddress))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(VenueAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(VenueCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VanueCreatebtn)
                                .addGap(57, 57, 57)
                                .addComponent(VanueUpdatebtn)
                                .addGap(56, 56, 56)
                                .addComponent(VanueViewbtn)
                                .addGap(52, 52, 52)
                                .addComponent(VanueDeletebtn)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))
                        .addGap(0, 61, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(VenueAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VenueName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(VenueAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(VenueCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VanueCreatebtn)
                    .addComponent(VanueUpdatebtn)
                    .addComponent(VanueViewbtn)
                    .addComponent(VanueDeletebtn)
                    .addComponent(jButton5))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VenueCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenueCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenueCapacityActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       AttendeeRegistration frame= new AttendeeRegistration();
       frame.setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void VanueCreatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VanueCreatebtnActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
              java.sql.Connection Vcon = DriverManager.getConnection("jdbc:mysql://localhost:3306/event_planner", "root", "Boitekong2003");
              
               String SQL2 = "INSERT INTO venue_management(Venue_Name,Venue_Address, Venue_Capacity,Venue_Availability) VALUES (?, ?, ?, ?)";
            PreparedStatement VState= Vcon.prepareCall(SQL2);
            

             VState.setString(1, VenueName.getText());
             VState.setString(2, VenueAddress.getText());
             VState.setString(3, VenueCapacity.getText());
             VState.setString(4, VenueAvailability.getText());
            
             VState.executeUpdate();
} catch (Exception ex) {
        if (((SQLException) ex).getErrorCode()==1062) {
JOptionPane.showMessageDialog(null,"Duplicate Entry");
}else {
      JOptionPane.showMessageDialog(null, "SQL Error "+ex.getMessage());      
        }
        }
        
          
    }//GEN-LAST:event_VanueCreatebtnActionPerformed
private void clear(){
      DefaultTableModel table = (DefaultTableModel)VanueTable.getModel();
        table.setRowCount(0);}
    private void VanueViewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VanueViewbtnActionPerformed
    clear();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection Viewconnection = DriverManager.getConnection("jdbc:mysql://localhost:3306/event_planner", "root", "Boitekong2003");
          Statement stm3 = Viewconnection.createStatement();
        String  sql4 = "SELECT * FROM venue_management";
        ResultSet Vresult = stm3.executeQuery(sql4);
        while(Vresult.next()){
        
            String VenueName=Vresult.getString("Venue_Name");
            String VenueAddress = Vresult.getString("Venue_Address");
            String VenueCapacity = Vresult.getString("Venue_Capacity");
            String VenueAvailability = Vresult.getString("Venue_Availability");
            
            String [] TableData ={VenueName,VenueAddress,VenueCapacity,VenueAvailability};
             DefaultTableModel table = (DefaultTableModel) VanueTable.getModel();
  table.addRow(TableData);
        
        
        }
        
        
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VanueManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VanueManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }//GEN-LAST:event_VanueViewbtnActionPerformed

    private void VanueUpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VanueUpdatebtnActionPerformed
       try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event_planner", "root", "Boitekong2003");
        String SQL2 = "UPDATE venue_management SET Venue_Name = ?, Venue_Address = ?, Venue_Capacity= ?,Venue_Availability= ?";
            
        PreparedStatement STATE = con.prepareStatement(SQL2);
                STATE.setString(1, VenueName.getText());
            STATE.setString(2, VenueAddress.getText());
            STATE.setString(3, VenueCapacity.getText());
            STATE.setString(4, VenueAvailability.getText());
           
          
            
            int rowsUpdated = STATE.executeUpdate();
             JOptionPane.showMessageDialog(null, "Successfully inserted the data to the database");
            if (rowsUpdated > 0) {
                
               JOptionPane.showMessageDialog(null,"Update successful");
            } else {
                
                JOptionPane.showMessageDialog(null,"Update failed");
            }
        } catch (SQLException ex) {
           
         JOptionPane.showMessageDialog(null,"Error updating data: " + ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EventPlanning.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_VanueUpdatebtnActionPerformed

    private void VanueUpdatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VanueUpdatebtnMouseClicked
  
    }//GEN-LAST:event_VanueUpdatebtnMouseClicked

    private void VanueTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VanueTableMouseClicked
           DefaultTableModel model2 = (DefaultTableModel) VanueTable.getModel();
           int row = VanueTable.rowAtPoint(evt.getPoint());
       
        int rows = VanueTable.getSelectedRowCount();

        if (rows == 1) {
       
        
        VenueName.setText(model2.getValueAt(row, 0).toString());
          VenueAddress.setText(model2.getValueAt(row, 1).toString());
          VenueCapacity.setText(model2.getValueAt(row, 2).toString());
          VenueAvailability.setText(model2.getValueAt(row, 3).toString());
           
      
}
    }//GEN-LAST:event_VanueTableMouseClicked

    private void VanueDeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VanueDeletebtnActionPerformed
 try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             java.sql.Connection con3 = DriverManager.getConnection("jdbc:mysql://localhost:3306/event_planner", "root", "Boitekong2003");
            
       String SQL = "DELETE FROM venue_management WHERE Venue_Name = ?";
PreparedStatement STATE4 = con3.prepareStatement(SQL);
            

            STATE4.setString(1, VenueName.getText());
            
            STATE4.executeUpdate();
         JOptionPane.showMessageDialog(null, "Successfully Deleted");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AttendeeRegistration.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Successfully Deleted");
        } catch (SQLException ex) {
            Logger.getLogger(AttendeeRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_VanueDeletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VanueManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VanueManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VanueManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VanueManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VanueManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VanueCreatebtn;
    private javax.swing.JButton VanueDeletebtn;
    private javax.swing.JTable VanueTable;
    private javax.swing.JButton VanueUpdatebtn;
    private javax.swing.JButton VanueViewbtn;
    private javax.swing.JTextField VenueAddress;
    private javax.swing.JTextField VenueAvailability;
    private javax.swing.JTextField VenueCapacity;
    private javax.swing.JTextField VenueName;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
